const CACHE_NAME = 'cache-media';

self.addEventListener('install', event => {
    event.waitUntil(
        caches.open(CACHE_NAME)
            .then(cache => {
                return cache.addAll([
                    '/css/style.css',
                    '/src/index.js',
                    "/media/Frames/Voligoma.Still.webp",
                    "/media/gifs/LOOPVoligoma1.webm",
                    "/media/Frames/ciclos.still.webp",
                    "/media/gifs/LOOPCiclos.webm",
                    "/media/Frames/tiburones.still1.webp",
                    "/media/gifs/LOOPTiburones.webm",
                    "/media/Frames/Chaino.Still.webp",
                    "/media/gifs/Chino.webm",
                    "/media/Frames/Ninpala.Still2.webp",
                    "/media/gifs/GotasDeSol.webm",
                    "/media/Frames/Malmo.Logan.Still.webp",
                    "/media/gifs/Malmo.webm",
                    "/media/Frames/Salvatores.Still2.webp",
                    "/media/gifs/Salvatores.webm",
                    "/media/Frames/Esquina.Margerite.Still.webp",
                    "/media/gifs/EsquinaAzul.webm",
                    "/media/Frames/Marciano.NB.Still.webp",
                    "/media/gifs/nb.webm",
                    "/media/Frames/Matandolaliga.Logan.Still.webp",
                    "/media/gifs/MatandoLaLiga.webm",
                    "/media/Frames/Enlasredes.Alset.Still.webp",
                    "/media/gifs/EnLasRedes.webm",
                    "/media/Frames/Lospapeles.Logan.Still.webp",
                    "/media/gifs/LosPapeles.webm",
                    "/media/Frames/Quest.Smoko.Still.webp",
                    "/media/gifs/Smoko.webm",
                    "/media/Frames/Octa.Still.webp",
                    "/media/gifs/Octa.webm",
                    "/media/Frames/Lenny.Theo.Still.webp",
                    "/media/gifs/Lenny.webm",
                    "/media/Frames/Cicatrices.Fibo.Still.webp",
                    "/media/gifs/Cicatrices.webm",
                    "/media/Frames/Elvisto.Hsmn.Still.webp",
                    "/media/gifs/ElVisto.webm",
                    "/media/Frames/Muchamecha.NB.Still.webp",
                    "/media/gifs/MuchaMecha.webm",
                    "/media/Frames/Metido.NB.Still.webp",
                    "/media/gifs/Metido.webm",
                    "/media/Frames/Bling.Coni.Still.webp",
                    "/media/gifs/Coni.webm",
                    "/media/Frames/Encandilo.Houseman.Still.webp",
                    "/media/gifs/Encandilo.webm",
                    "/media/Frames/Sesionespicantes.Still.webp",
                    "/media/gifs/SesionesPicantes.webm",
                    "/media/trabajosP/estacionVictoria/CUBAFEDD23.webp",
                    "/media/trabajosP/estacionVictoria/CUBAFEED11.webp",
                    "/media/trabajosP/estacionVictoria/CUBAFEED15.webp",
                    "/media/trabajosP/estacionVictoria/CUBAFEED20.webp",
                    "/media/trabajosP/estacionVictoria/CUBAFEED9.webp",
                    "/media/trabajosP/estacionVictoria/Reel1Final_HD.gif",
                    "/media/trabajosP/estacionVictoria/Reel2Final_HD.gif",
                    "/media/trabajosP/estacionVictoria/Reelcubafinal4.gif",
                    "/media/trabajosP/elevenFlow/fedefeed.webp",
                    "/media/trabajosP/elevenFlow/FeedAGOS2.webp",
                    "/media/trabajosP/elevenFlow/FeedAITI.webp",
                    "/media/trabajosP/elevenFlow/Pipifeed.webp",
                    "/media/trabajosP/elevenFlow/zapas.webp",
                    "/media/trabajosP/instaburger/INSTA15.webp",
                    "/media/trabajosP/instaburger/INSTA17.webp",
                    "/media/trabajosP/instaburger/INSTA20.webp",
                    "/media/trabajosP/instaburger/INSTA3.webp",
                    "/media/trabajosP/instaburger/INSTAb7.webp",
                    "/media/trabajosP/nico_padilla/Nico1-10.webp",
                    "/media/trabajosP/nico_padilla/Nico1-16.webp",
                    "/media/trabajosP/nico_padilla/Nico1-4.webp",
                    "/media/trabajosP/prospero/prospero1-8171.webp",
                    "/media/trabajosP/prospero/prospero12c-04239.webp",
                    "/media/trabajosP/prospero/prospero2-8155.webp",
                    "/media/trabajosP/prospero/prospero3-8142.webp",
                    "/media/trabajosP/prospero/prospero9-8114.webp",
                    "/media/trabajosP/prospero/prosperox-8027.webp",
                    "/media/trabajosP/marioGonzalez/2.webp",
                    "/media/trabajosP/marioGonzalez/22.webp",
                    "/media/trabajosP/marioGonzalez/4.webp",
                    "/media/trabajosP/marioGonzalez/6.webp",
                    "/media/trabajosP/veneno/2.webp",
                    "/media/trabajosP/veneno/3.webp",
                    "/media/trabajosP/veneno/4.webp",
                    "/media/trabajosP/veneno/9.webp",
                    "/media/trabajosP/blfreestyle/reelblFINAL.gif",
                    "/media/trabajosP/blfreestyle/secuencia01_2.gif",
                    "/media/trabajosP/naza_guitierrez/nazabook1.webp",
                    "/media/trabajosP/naza_guitierrez/nazabook2.webp",
                    "/media/trabajosP/naza_guitierrez/nazapan3fin.webp",
                    "/media/trabajosP/naza_guitierrez/nazasuperfinal2.webp",
                    "/media/trabajosP/naza_guitierrez/nazasuperfinal3.webp",
                    "/media/reelpaginafinal.webm",
                    "/media/integrantes/agus.webp",
                    "/media/integrantes/gaston.webp",
                    "/media/integrantes/naza.webp",
                    "/media/integrantes/nahuel.webp",
                    "/media/carouselContacto/carouselContacto_11.webp",
                    "/media/carouselContacto/carouselContacto_1.webp",
                    "/media/carouselContacto/carouselContacto_10.webp",
                    "/media/carouselContacto/carouselContacto_2.webp",
                    "/media/carouselContacto/carouselContacto_3.webp",
                    "/media/carouselContacto/carouselContacto_4.webp",
                    "/media/carouselContacto/carouselContacto_5.webp",
                    "/media/carouselContacto/carouselContacto_6.webp",
                    "/media/carouselContacto/carouselContacto_7.webp",
                    "/media/carouselContacto/carouselContacto_8.webp",
                    "/media/carouselContacto/carouselContacto_9.webp"
                ]);
            })
    );
});

self.addEventListener('fetch', event => {
    event.respondWith(
        caches.match(event.request)
            .then(response => {
                if (response) {
                    // Retorna la imagen desde la caché
                    return response;
                }

                // Si no está en la caché, realiza la solicitud de red
                return fetch(event.request);
            })
    );
});

// "https://res.cloudinary.com/dionldpu0/video/upload/v1684447562/Atlanta/reelpaginafinal_pa6ctk.webm",
                    // 'https://res.cloudinary.com/dionldpu0/image/upload/v1683899942/Atlanta/frames/Voligoma.Still_egt7sa.webp',
                    // 'https://res.cloudinary.com/dionldpu0/video/upload/v1683900680/Atlanta/gifs/LOOPVoligoma1_mda2uu.mp4',
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683899943/Atlanta/frames/ciclos.still_ibl3wj.webp",
                    // "https://res.cloudinary.com/dionldpu0/video/upload/v1683900648/Atlanta/gifs/LOOPCiclos_rzlxza.mp4",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683899942/Atlanta/frames/tiburones.still1_rsopr1.webp",
                    // "https://res.cloudinary.com/dionldpu0/video/upload/v1683900594/Atlanta/gifs/LOOPTiburones_ttv82q.mp4",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683899942/Atlanta/frames/Chaino.Still_e8oenp.webp",
                    // "https://res.cloudinary.com/dionldpu0/video/upload/v1683900516/Atlanta/gifs/Chino_uotofa.mp4",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683899940/Atlanta/frames/Ninpala.Still2_orrsls.webp",
                    // "https://res.cloudinary.com/dionldpu0/video/upload/v1683900534/Atlanta/gifs/GotasDeSol_efzbza.mp4",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683899939/Atlanta/frames/Malmo.Logan.Still_lfzcnc.webp",
                    // "https://res.cloudinary.com/dionldpu0/video/upload/v1683900580/Atlanta/gifs/Malmo_aoujtm.mp4",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683899941/Atlanta/frames/Salvatores.Still2_pwtr1v.webp",
                    // "https://res.cloudinary.com/dionldpu0/video/upload/v1683900659/Atlanta/gifs/Salvatores_tf7roi.mp4",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683899944/Atlanta/frames/Esquina.Margerite.Still_k5gwms.webp",
                    // "https://res.cloudinary.com/dionldpu0/video/upload/v1683900522/Atlanta/gifs/EsquinaAzul_ors9jz.mp4",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683899939/Atlanta/frames/Marciano.NB.Still_et7w7l.webp",
                    // "https://res.cloudinary.com/dionldpu0/video/upload/v1683900517/Atlanta/gifs/nb_mu8mpm.mp4",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683899940/Atlanta/frames/Matandolaliga.Logan.Still_il9gec.webp",
                    // "https://res.cloudinary.com/dionldpu0/video/upload/v1683900502/Atlanta/gifs/MatandoLaLiga_wonntd.mp4",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683899943/Atlanta/frames/Enlasredes.Alset.Still_zor0ve.webp",
                    // "https://res.cloudinary.com/dionldpu0/video/upload/v1683900625/Atlanta/gifs/EnLasRedes_mdvdf5.mp4",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683899939/Atlanta/frames/Lospapeles.Logan.Still_clixk4.webp",
                    // "https://res.cloudinary.com/dionldpu0/video/upload/v1683900529/Atlanta/gifs/LosPapeles_uhm4ub.mp4",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683899941/Atlanta/frames/Quest.Smoko.Still_tb8kkk.webp",
                    // "https://res.cloudinary.com/dionldpu0/video/upload/v1683900555/Atlanta/gifs/Smoko_p2tkh6.mp4",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683899941/Atlanta/frames/Octa.Still_bwqffi.webp",
                    // "https://res.cloudinary.com/dionldpu0/video/upload/v1683900526/Atlanta/gifs/Octa_ze95kx.mp4",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683899939/Atlanta/frames/Lenny.Theo.Still_vvg2a8.webp",
                    // "https://res.cloudinary.com/dionldpu0/video/upload/v1683900640/Atlanta/gifs/Lenny_yo7dyc.mp4",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683899942/Atlanta/frames/Cicatrices.Fibo.Still_mlhukz.webp",
                    // "https://res.cloudinary.com/dionldpu0/video/upload/v1683900622/Atlanta/gifs/Cicatrices_mknbnr.mp4",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683899942/Atlanta/frames/Elvisto.Hsmn.Still_1_pnmgrx.webp",
                    // "https://res.cloudinary.com/dionldpu0/video/upload/v1683900622/Atlanta/gifs/ElVisto_nvuxtz.mp4",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683899940/Atlanta/frames/Muchamecha.NB.Still_kiakcu.webp",
                    // "https://res.cloudinary.com/dionldpu0/video/upload/v1683900586/Atlanta/gifs/MuchaMecha_jogt17.mp4",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683899940/Atlanta/frames/Metido.NB.Still_oilxih.webp",
                    // "https://res.cloudinary.com/dionldpu0/video/upload/v1683900510/Atlanta/gifs/Metido_crivci.mp4",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683899942/Atlanta/frames/Bling.Coni.Still_ltig8y.webp",
                    // "https://res.cloudinary.com/dionldpu0/video/upload/v1683900534/Atlanta/gifs/Coni_iamoty.mp4",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683899943/Atlanta/frames/Encandilo.Houseman.Still_b3hngf.webp",
                    // "https://res.cloudinary.com/dionldpu0/video/upload/v1683900566/Atlanta/gifs/Encandilo_irqtfv.mp4",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683899942/Atlanta/frames/Sesionespicantes.Still_grkzsq.webp",
                    // "https://res.cloudinary.com/dionldpu0/video/upload/v1683900555/Atlanta/gifs/SesionesPicantes_hmxa7r.mp4",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904196/Atlanta/trabajosP/estacionVictoria/CUBAFEDD23_diomov.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904196/Atlanta/trabajosP/estacionVictoria/CUBAFEED15_d0v7mc.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904196/Atlanta/trabajosP/estacionVictoria/CUBAFEED20_lbzzqj.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904196/Atlanta/trabajosP/estacionVictoria/CUBAFEED11_m8owoy.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904197/Atlanta/trabajosP/estacionVictoria/CUBAFEED9_m5qh7l.webp",
                    // "https://res.cloudinary.com/dionldpu0/video/upload/v1683904214/Atlanta/trabajosP/estacionVictoria/Reel2Final_HD_qvdghs.webm",
                    // "https://res.cloudinary.com/dionldpu0/video/upload/v1683904219/Atlanta/trabajosP/estacionVictoria/Reel1Final_HD_yztzjf.webm",
                    // "https://res.cloudinary.com/dionldpu0/video/upload/v1683904220/Atlanta/trabajosP/estacionVictoria/Reelcubafinal4_evt5ki.webm",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904211/Atlanta/trabajosP/elevenFlow/fedefeed_fttjs6.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904220/Atlanta/trabajosP/elevenFlow/FeedAITI_rokv9e.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904220/Atlanta/trabajosP/elevenFlow/Pipifeed_jwwoeu.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904197/Atlanta/trabajosP/elevenFlow/FeedAGOS2_rbeyms.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904197/Atlanta/trabajosP/elevenFlow/zapas_cq16hn.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904199/Atlanta/trabajosP/instaburger/INSTA15_p5zqft.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904199/Atlanta/trabajosP/instaburger/INSTAb7_umtd4e.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904198/Atlanta/trabajosP/instaburger/INSTA20_kw6dqv.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904198/Atlanta/trabajosP/instaburger/INSTA3_nra3j2.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904198/Atlanta/trabajosP/instaburger/INSTA17_apgeos.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904207/Atlanta/trabajosP/nico_padilla/Nico1-39_ijswaa.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904204/Atlanta/trabajosP/nico_padilla/Nico1-10_bh6hed.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904204/Atlanta/trabajosP/nico_padilla/Nico1-16_nabcij.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904204/Atlanta/trabajosP/nico_padilla/Nico1-4_m2qyi1.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904205/Atlanta/trabajosP/prospero/prosperox-8027_qtpzsh.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904205/Atlanta/trabajosP/prospero/prospero3-8142_l22n6k.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904205/Atlanta/trabajosP/prospero/prospero9-8114_ivp60t.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904204/Atlanta/trabajosP/prospero/prospero2-8155_tdmfss.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904204/Atlanta/trabajosP/prospero/prospero12c-04239_fsxhhk.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904203/Atlanta/trabajosP/prospero/prospero1-8171_pqh8va.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904201/Atlanta/trabajosP/marioGonzalez/6_atpwex.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904201/Atlanta/trabajosP/marioGonzalez/4_wrgjvp.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904200/Atlanta/trabajosP/marioGonzalez/2_lpq4h0.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904200/Atlanta/trabajosP/marioGonzalez/22_n9tger.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904219/Atlanta/trabajosP/veneno/3_gwlpyy.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904216/Atlanta/trabajosP/veneno/2_h4e3ql.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904211/Atlanta/trabajosP/veneno/4_w4vpzk.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904207/Atlanta/trabajosP/veneno/9_n4ldd5.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904211/Atlanta/trabajosP/veneno/Facuext-8_zkt8z6.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904211/Atlanta/trabajosP/veneno/Facuext-5_i0zynh.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904208/Atlanta/trabajosP/veneno/Facuext-11_xiokag.webp",
                    // "https://res.cloudinary.com/dionldpu0/video/upload/v1683904214/Atlanta/trabajosP/blfreestyle/reelblFINAL_wqcrlb.webm",
                    // "https://res.cloudinary.com/dionldpu0/video/upload/v1683904211/Atlanta/trabajosP/blfreestyle/secuencia01_2_hgtygg.webm",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904201/Atlanta/trabajosP/naza_guitierrez/nazasuperfinal3_x6u6s3.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904201/Atlanta/trabajosP/naza_guitierrez/nazasuperfinal2_iirx9q.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904201/Atlanta/trabajosP/naza_guitierrez/nazabook1_twcyaw.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904201/Atlanta/trabajosP/naza_guitierrez/nazapan3fin_hncbw0.webp",
                    // "https://res.cloudinary.com/dionldpu0/image/upload/v1683904200/Atlanta/trabajosP/naza_guitierrez/nazabook2_nlpshq.webp",
